name: retarget
description: supports conditional compilation of platform-specific Flutter UI code using \#if and \#switch pragmas.
version: 0.1.1
homepage: https://github.com/ohir/retarget
repository: https://github.com/ohir/retarget

executables:
  retarget:

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  path: ^1.8.2
  args: ^2.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
